version: '3.8'

services:
  mongo:
    image: mongo
    container_name: mongo_db
    restart: always
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db

  backend:
    build: .
    container_name: node_backend
    restart: always
    ports:
      - '5000:5000'
    depends_on:
      - mongo
    env_file:
      - .env
    environment:
      - MONGO_URI=mongodb://mongo:27017/authdb
      - JWT_SECRET=${JWT_SECRET}
      - PORT=${PORT}
    volumes:
      - .:/app

volumes:
  mongo-data:
